apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- geolin-back.yaml
- postgres.yaml
- mongo.yaml
- problems.yaml
- backend.yaml
- front.yaml
- servicemonitor.yaml
- video.yaml
