apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: actual-tls
  namespace: actual
spec:
  secretName: actual.mgsds.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: actual.mgsds.com
  dnsNames:
    - actual.mgsds.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: actual
  name: actual-ingress-mtls
  labels:
    app.kubernetes.io/name: actual-ingress-mtls
    app.kubernetes.io/component: ingress
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - actual.mgsds.com
      secretName: actual.mgsds.com-tls
  rules:
    - host: actual.mgsds.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: actual-actualbudget
                port:
                  number: 5006
