apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pocket-id-tls
  namespace: pocket-id
spec:
  secretName: pocket-id.mgsds.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pocket-id.mgsds.com
  dnsNames:
  - pocket-id.mgsds.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: pocket-id
  name: pocket-id-ingress-tls
  labels:
    app.kubernetes.io/name: pocket-id-ingress-tls
    app.kubernetes.io/component: ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - pocket-id.mgsds.com
    secretName: pocket-id.mgsds.com-tls
  rules:
  - host: pocket-id.mgsds.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pocket-id
            port:
              number: 80 